"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const courierMiddleware_1 = require("../middleware/courierMiddleware");
const courierController_1 = require("../controllers/courierController");
const authMiddleware_1 = require("../middleware/authMiddleware");
const adminMiddleware_1 = require("../middleware/adminMiddleware");
const courierRoute = express_1.default.Router();
courierRoute.post("/applications", authMiddleware_1.authMiddleware, courierController_1.createApplication);
courierRoute.get("/applications/status", authMiddleware_1.authMiddleware, courierController_1.checkIfSentApplication);
courierRoute.get("/applications", adminMiddleware_1.adminMiddleware, courierController_1.getApplications);
courierRoute.get("/profile", courierMiddleware_1.courierMiddleware, courierController_1.profile);
courierRoute.post("/orders/:id/take", courierMiddleware_1.courierMiddleware, courierController_1.takeOrder);
courierRoute.get("/orders/:id/status", courierController_1.checkIfHasOrder);
courierRoute.patch("/orders/:id/status", courierMiddleware_1.courierMiddleware, courierController_1.changeOrderStatus);
courierRoute.post("/applications/:id", courierController_1.toggleApplication);
exports.default = courierRoute;
