"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const authMiddleware_1 = require("../middleware/authMiddleware");
const orderController_1 = require("../controllers/orderController");
const courierMiddleware_1 = require("../middleware/courierMiddleware");
const adminMiddleware_1 = require("../middleware/adminMiddleware");
const restaurantMiddleware_1 = require("../middleware/restaurantMiddleware");
const dashboardMiddleware_1 = require("../middleware/dashboardMiddleware");
const orderRoute = express_1.default.Router();
orderRoute.post("/orders", authMiddleware_1.authMiddleware, orderController_1.createOrder);
orderRoute.patch("/orders", authMiddleware_1.authMiddleware, orderController_1.updateOrder);
orderRoute.get("/orders", authMiddleware_1.authMiddleware, orderController_1.getOrders);
orderRoute.get("/orders/recent", adminMiddleware_1.adminMiddleware, orderController_1.getLastSevenOrders);
orderRoute.get("/orders/statistics", dashboardMiddleware_1.dashboardMiddleware, orderController_1.getNumbers);
orderRoute.get("/restaurants/:id/orders/recent", restaurantMiddleware_1.restaurantMiddleware, orderController_1.getLastSevenOrders);
orderRoute.patch("/orders/:id/status", restaurantMiddleware_1.restaurantMiddleware, orderController_1.toggleToPreparing);
orderRoute.get("/orders/:id/created", restaurantMiddleware_1.restaurantMiddleware, orderController_1.getOrdersCreated);
orderRoute.get("/couriers/:id/orders", courierMiddleware_1.courierMiddleware, orderController_1.getOrdersCourier);
orderRoute.get("/free-orders/:city", courierMiddleware_1.courierMiddleware, orderController_1.getFreeOrders);
orderRoute.get("/orders/:id", authMiddleware_1.authMiddleware, orderController_1.getOrder);
exports.default = orderRoute;
