"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const restaurantController_1 = require("../controllers/restaurantController");
const authMiddleware_1 = require("../middleware/authMiddleware");
const adminMiddleware_1 = require("../middleware/adminMiddleware");
const restaurantMiddleware_1 = require("../middleware/restaurantMiddleware");
const restaurantRoute = express_1.default.Router();
restaurantRoute.post("/restaurants", restaurantController_1.createItem);
restaurantRoute.get("/restaurants/filter", restaurantController_1.getRestaurantsFiltered);
restaurantRoute.get("/restaurants/search", restaurantController_1.searchRestaurants);
restaurantRoute.get("/restaurants/favourites", authMiddleware_1.authMiddleware, restaurantController_1.getFavouriteRestaurants);
restaurantRoute.get("/dishes/nearby", restaurantController_1.getDishesNearYou);
restaurantRoute.post("/reviews", authMiddleware_1.authMiddleware, restaurantController_1.createReview);
restaurantRoute.get("/restaurants/reviews/recent", adminMiddleware_1.adminMiddleware, restaurantController_1.getLastSevenReviews);
restaurantRoute.get("/restaurants/dishes/top", adminMiddleware_1.adminMiddleware, restaurantController_1.getTopSevenDishes);
restaurantRoute.post("/dishes", restaurantController_1.createDish);
restaurantRoute.get("/restaurants/:id/reviews/recent", restaurantMiddleware_1.restaurantMiddleware, restaurantController_1.getLastSevenReviews);
restaurantRoute.get("/restaurants/:id/dishes/top", restaurantMiddleware_1.restaurantMiddleware, restaurantController_1.getTopSevenDishes);
restaurantRoute.get("/restaurants/:title/address", restaurantController_1.getRestaurantAddress);
restaurantRoute.post("/restaurants/:id/favourite", authMiddleware_1.authMiddleware, restaurantController_1.toggleFavourite);
restaurantRoute.post("/restaurants/:id/about", restaurantController_1.handleAbout);
restaurantRoute.get("/restaurants/:id/about", restaurantController_1.getAbout);
restaurantRoute.get("/restaurants/:id/reviews", restaurantController_1.getReviews);
restaurantRoute.get("/restaurants/:id", restaurantController_1.getRestaurantById);
restaurantRoute.get("/dishes/:id", restaurantController_1.getDishes);
restaurantRoute.delete("/dishes/:id", restaurantController_1.deleteDish);
exports.default = restaurantRoute;
