export * as authApi from "./auth";
export * as restaurantsApi from "./restaurants";
export * as cartApi from "./cart";
export * as ordersApi from "./orders";
export * as courierApi from "./courier";
export * as addressesApi from "./addresses";
export * as promocodesApi from "./promocodes";
export * as ratingsApi from "./ratings";
export * as paymentsApi from "./payments";
export * as geocodeApi from "./geocode";
export * as demoApi from "./demo";
export { apiClient, errorMessage, isNotFound, isUnauthorized } from "@/lib/apiClient";
