import {
  ArrowRight,
  BadgeCheck,
  Bike,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Clock3,
  CreditCard,
  Heart,
  Home,
  MapPin,
  Minus,
  Navigation,
  PackageCheck,
  Plus,
  Search,
  ShoppingBag,
  Sparkles,
  Star,
  Store,
  UtensilsCrossed,
} from "lucide-react";
import Image from "next/image";

export const foodieHubScreens = ["discover", "checkout", "tracking"] as const;
export type FoodieHubScreen = (typeof foodieHubScreens)[number];

function Wordmark() {
  return <div className="flex items-center gap-2"><span className="flex size-10 items-center justify-center rounded-xl bg-brand text-onBrand"><UtensilsCrossed size={21}/></span><div><p className="font-display text-xl font-extrabold leading-none text-ink">FoodieHub</p><p className="mt-1 text-[10px] font-bold uppercase tracking-widest text-brand">Local. Fast. Fresh.</p></div></div>;
}

function Shell({ screen, children }: { screen: FoodieHubScreen; children: React.ReactNode }) {
  const nav = [{ label: "Discover", screen: "discover" }, { label: "Restaurants", screen: "restaurants" }, { label: "My orders", screen: "tracking" }];
  return <div className="min-h-screen bg-bg text-ink"><header className="border-b border-border bg-surface"><div className="mx-auto flex h-[76px] max-w-[1400px] items-center gap-8 px-8"><Wordmark/><nav className="flex items-center gap-1">{nav.map((item)=><span key={item.label} className={`rounded-lg px-4 py-2 text-sm font-semibold ${item.screen===screen ? "bg-ember-50 text-brand" : "text-inkMuted"}`}>{item.label}</span>)}</nav><div className="ml-auto flex items-center gap-3"><div className="flex w-80 items-center gap-3 rounded-xl border border-border bg-bg px-4 py-2.5 text-sm text-inkMuted"><Search size={17}/>Search dishes or restaurants</div><div className="relative flex size-11 items-center justify-center rounded-xl border border-border bg-surface"><ShoppingBag size={19}/><span className="absolute -right-1.5 -top-1.5 flex size-5 items-center justify-center rounded-full bg-brand text-[10px] font-bold text-onBrand">3</span></div><span className="flex size-11 items-center justify-center rounded-full bg-teal-100 font-bold text-teal-800">BT</span></div></div></header><main className="mx-auto max-w-[1400px] px-8 py-6">{children}</main></div>;
}

function SectionHeader({ eyebrow, title, text, action }: { eyebrow: string; title: string; text: string; action?: React.ReactNode }) {
  return <header className="mb-6 flex items-end justify-between gap-6"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-brand">{eyebrow}</p><h1 className="mt-1 font-display text-4xl font-extrabold tracking-tight text-ink">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-inkMuted">{text}</p></div>{action}</header>;
}

const restaurants = [
  { name: "Ember & Stone", cuisine: "Artisan pizza · Mediterranean", rating: "4.9", time: "20–30 min", position: "70% 45%", offer: "20% off" },
  { name: "Green Table", cuisine: "Bowls · Healthy · Vegan", rating: "4.8", time: "25–35 min", position: "45% 95%", offer: "Free delivery" },
  { name: "Sourdough Social", cuisine: "Bakery · Brunch · Coffee", rating: "4.7", time: "15–25 min", position: "96% 88%", offer: "New" },
];

function Discover() {
  return <><section className="relative h-[360px] overflow-hidden rounded-[28px] bg-sand-900"><Image src="/images/foodiehub-hero-v2.png" alt="Artisan pizza and Mediterranean dishes" fill priority sizes="1400px" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-sand-950/95 via-sand-950/60 to-transparent"/><div className="relative flex h-full max-w-xl flex-col justify-center px-10 text-white"><span className="flex w-fit items-center gap-2 rounded-full bg-white/15 px-3 py-1.5 text-xs font-bold backdrop-blur"><Sparkles size={14}/>Curated near you</span><h1 className="mt-5 font-display text-5xl font-extrabold leading-[1.04]">Your city’s best food, at your door.</h1><p className="mt-4 max-w-lg text-base leading-7 text-white/85">Discover local favorites, live delivery tracking, and meals worth staying in for.</p><div className="mt-6 flex w-[470px] items-center rounded-xl bg-white p-2 shadow-elevation4"><div className="flex flex-1 items-center gap-3 px-3 text-sm text-sand-600"><MapPin size={18} className="text-ember-700"/>12 Market Street, Kyiv</div><div className="rounded-lg bg-ember-700 px-5 py-3 text-sm font-bold text-white">Find food</div></div></div></section>
    <section className="mt-6 flex items-center gap-3">{[["🔥","Popular"],["🍕","Pizza"],["🥗","Healthy"],["🍜","Asian"],["🍔","Burgers"],["🥐","Bakery"],["☕","Coffee"]].map(([icon,label],index)=><div key={label} className={`flex items-center gap-2 rounded-full border px-4 py-2.5 text-sm font-bold ${index===0 ? "border-ember-200 bg-ember-50 text-ember-800" : "border-border bg-surface text-ink"}`}><span>{icon}</span>{label}</div>)}<div className="ml-auto flex items-center gap-2 text-sm font-bold text-brand">All categories <ArrowRight size={16}/></div></section>
    <section className="mt-7"><div className="mb-4 flex items-end justify-between"><div><h2 className="font-display text-2xl font-extrabold">Top picks near you</h2><p className="mt-1 text-sm text-inkMuted">Hand-picked from the best local kitchens</p></div><div className="flex items-center gap-2 rounded-lg border bg-surface px-3 py-2 text-sm font-semibold text-inkMuted">Delivery now <ChevronDown size={15}/></div></div><div className="grid grid-cols-3 gap-4">{restaurants.map((restaurant)=><article key={restaurant.name} className="overflow-hidden rounded-2xl border border-border bg-surface shadow-elevation2"><div className="relative h-40 overflow-hidden"><Image src="/images/foodiehub-hero-v2.png" alt="" fill sizes="420px" className="scale-150 object-cover" style={{ objectPosition: restaurant.position }}/><span className="absolute left-3 top-3 rounded-full bg-surface/95 px-3 py-1.5 text-xs font-extrabold text-brand shadow-elevation1">{restaurant.offer}</span><span className="absolute right-3 top-3 flex size-9 items-center justify-center rounded-full bg-surface/95 text-ink"><Heart size={17}/></span></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-display text-lg font-extrabold">{restaurant.name}</h3><p className="mt-1 text-xs text-inkMuted">{restaurant.cuisine}</p></div><div className="flex items-center gap-1 rounded-lg bg-teal-100 px-2 py-1 text-xs font-bold text-teal-800"><Star size={13} fill="currentColor"/>{restaurant.rating}</div></div><div className="mt-4 flex items-center gap-4 text-xs font-semibold text-inkMuted"><span className="flex items-center gap-1.5"><Clock3 size={14}/>{restaurant.time}</span><span>€0 delivery</span><span className="ml-auto flex items-center gap-1 text-brand">View menu <ChevronRight size={14}/></span></div></div></article>)}</div></section>
  </>;
}

function Qty({ value }: { value: number }) { return <div className="flex items-center gap-3 rounded-lg border border-border bg-surface px-2 py-1.5"><Minus size={14} className="text-inkMuted"/><span className="min-w-4 text-center text-sm font-bold">{value}</span><Plus size={14} className="text-brand"/></div>; }

function Checkout() {
  return <><SectionHeader eyebrow="Secure checkout" title="One last step to dinner" text="Review your order, delivery details, and payment before the kitchen starts cooking." action={<div className="flex items-center gap-2 rounded-xl bg-teal-100 px-4 py-3 text-sm font-bold text-teal-800"><BadgeCheck size={18}/>Encrypted payment</div>}/>
    <div className="grid gap-5 lg:grid-cols-[1fr_25rem]"><div className="space-y-4"><section className="rounded-2xl border border-border bg-surface p-6 shadow-elevation1"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-xl bg-ember-50 text-brand"><Store size={20}/></span><div><h2 className="font-display text-lg font-extrabold">Ember & Stone</h2><p className="mt-0.5 text-xs text-inkMuted">Estimated delivery · 20–30 min</p></div></div><span className="text-sm font-bold text-brand">Add items</span></div><div className="mt-5 divide-y divide-border">{[["Margherita D.O.P.","Tomato, fior di latte, basil","€14.50",1,"70% 45%"],["Roasted vegetable plate","Herbs, tahini, sourdough","€11.00",1,"93% 8%"],["Mediterranean bowl","Hummus, feta, chickpeas","€12.50",1,"45% 95%"]].map(([name,desc,price,qty,pos])=><div key={name as string} className="grid grid-cols-[5rem_1fr_auto_auto] items-center gap-4 py-4"><div className="relative h-16 overflow-hidden rounded-xl"><Image src="/images/foodiehub-hero-v2.png" alt="" fill sizes="80px" className="scale-150 object-cover" style={{objectPosition: pos as string}}/></div><div><p className="text-sm font-bold">{name as string}</p><p className="mt-1 text-xs text-inkMuted">{desc as string}</p></div><Qty value={qty as number}/><p className="w-16 text-right text-sm font-extrabold">{price as string}</p></div>)}</div></section>
      <section className="grid grid-cols-2 gap-4"><div className="rounded-2xl border border-border bg-surface p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-teal-100 text-teal-800"><Home size={18}/></span><div><p className="text-sm font-bold">Delivery address</p><p className="mt-0.5 text-xs text-inkMuted">Home</p></div></div><span className="text-xs font-bold text-brand">Change</span></div><p className="mt-4 text-sm leading-6 text-inkMuted">12 Market Street, Apt 24<br/>Kyiv, 01001</p></div><div className="rounded-2xl border border-border bg-surface p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-info100 text-info800"><CreditCard size={18}/></span><div><p className="text-sm font-bold">Payment method</p><p className="mt-0.5 text-xs text-inkMuted">Visa ending 4242</p></div></div><span className="text-xs font-bold text-brand">Change</span></div><div className="mt-4 flex items-center gap-3 rounded-lg bg-sand-100 px-3 py-2 text-xs font-semibold text-sand-700"><span className="font-extrabold italic">VISA</span>•••• 4242 <span className="ml-auto">09/29</span></div></div></section>
    </div><aside className="h-fit rounded-2xl border border-border bg-surface p-6 shadow-elevation3"><h2 className="font-display text-xl font-extrabold">Order summary</h2><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between text-inkMuted"><span>Subtotal</span><span>€38.00</span></div><div className="flex justify-between text-inkMuted"><span>Delivery fee</span><span className="font-bold text-teal-800">Free</span></div><div className="flex justify-between text-inkMuted"><span>Service fee</span><span>€2.50</span></div><div className="flex justify-between text-brand"><span>WELCOME20</span><span>−€7.60</span></div></div><div className="my-5 border-t border-dashed border-border"/><div className="flex items-end justify-between"><span className="font-bold">Total</span><div className="text-right"><p className="font-display text-3xl font-extrabold">€32.90</p><p className="text-[10px] text-inkMuted">VAT included</p></div></div><div className="mt-6 flex items-center justify-center gap-2 rounded-xl bg-brand px-5 py-4 text-sm font-extrabold text-onBrand">Place order · €32.90 <ArrowRight size={17}/></div><p className="mt-4 text-center text-[11px] leading-5 text-inkMuted">By placing this order, you agree to FoodieHub’s terms and refund policy.</p><div className="mt-5 flex items-center justify-center gap-4 border-t border-border pt-4 text-[10px] font-bold uppercase tracking-wider text-inkSubtle"><span>Stripe</span><span>SSL secure</span><span>3D Secure</span></div></aside></div>
  </>;
}

function Tracking() {
  return <><SectionHeader eyebrow="Live delivery" title="Your dinner is on the way" text="Follow order #FH-2841 from the restaurant kitchen to your door in real time." action={<div className="rounded-xl border border-border bg-surface px-4 py-3 text-sm font-bold">Help with this order</div>}/>
    <div className="grid gap-5 lg:grid-cols-[1.45fr_.55fr]"><section className="relative min-h-[650px] overflow-hidden rounded-2xl border border-border bg-sand-100 shadow-elevation2"><div className="absolute inset-0 opacity-80" style={{backgroundImage:"linear-gradient(30deg, transparent 46%, var(--sand-300) 47%, var(--sand-300) 49%, transparent 50%), linear-gradient(120deg, transparent 46%, var(--sand-300) 47%, var(--sand-300) 49%, transparent 50%)",backgroundSize:"140px 140px"}}/><div className="absolute inset-x-12 top-10 rounded-2xl border border-border bg-surface/95 p-4 shadow-elevation3 backdrop-blur"><div className="flex items-center gap-4"><span className="flex size-11 items-center justify-center rounded-xl bg-teal-100 text-teal-800"><Bike size={21}/></span><div><p className="text-sm font-extrabold">Alex is 8 minutes away</p><p className="mt-0.5 text-xs text-inkMuted">Your order is hot, packed, and moving</p></div><div className="ml-auto rounded-full bg-teal-100 px-3 py-1.5 text-xs font-bold text-teal-800">On time</div></div></div><svg className="absolute inset-0 h-full w-full" viewBox="0 0 900 650" preserveAspectRatio="none"><path d="M180 505 C270 455 265 355 380 340 S520 335 575 250 S705 210 755 125" fill="none" stroke="white" strokeWidth="12" strokeLinecap="round"/><path d="M180 505 C270 455 265 355 380 340 S520 335 575 250 S705 210 755 125" fill="none" stroke="var(--teal-600)" strokeWidth="5" strokeDasharray="10 8" strokeLinecap="round"/></svg><div className="absolute bottom-[122px] left-[142px] flex size-14 items-center justify-center rounded-full border-4 border-surface bg-brand text-onBrand shadow-elevation3"><Home size={23}/></div><div className="absolute right-[14%] top-[15%] flex size-14 items-center justify-center rounded-full border-4 border-surface bg-sand-900 text-white shadow-elevation3"><Store size={23}/></div><div className="absolute left-[56%] top-[35%] flex size-14 items-center justify-center rounded-full border-4 border-surface bg-teal-700 text-white shadow-elevation4"><Bike size={24}/></div><div className="absolute bottom-5 left-5 right-5 flex items-center rounded-2xl border border-border bg-surface/95 p-4 shadow-elevation3 backdrop-blur"><span className="flex size-12 items-center justify-center rounded-full bg-teal-100 font-extrabold text-teal-800">AO</span><div className="ml-3"><p className="text-sm font-extrabold">Alex O.</p><div className="mt-1 flex items-center gap-2 text-xs text-inkMuted"><Star size={13} fill="currentColor" className="text-warning700"/>4.9 · 486 deliveries</div></div><div className="ml-auto flex gap-2"><div className="rounded-xl border border-border px-4 py-2.5 text-sm font-bold">Message</div><div className="flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-bold text-white"><Navigation size={16}/>Track live</div></div></div></section>
      <aside className="space-y-4"><section className="rounded-2xl border border-border bg-surface p-6 shadow-elevation1"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-brand">Order #FH-2841</p><h2 className="mt-2 font-display text-xl font-extrabold">Ember & Stone</h2></div><span className="flex size-10 items-center justify-center rounded-xl bg-ember-50 text-brand"><UtensilsCrossed size={18}/></span></div><div className="mt-6 space-y-0">{[{icon:CheckCircle2,title:"Order confirmed",time:"18:42",done:true},{icon:PackageCheck,title:"Prepared & packed",time:"19:03",done:true},{icon:Bike,title:"Out for delivery",time:"19:08",done:true},{icon:Home,title:"Delivered",time:"Est. 19:26",done:false}].map((item,index)=>{const Icon=item.icon;return <div key={item.title} className="relative flex gap-4 pb-6 last:pb-0">{index<3?<span className={`absolute left-[17px] top-9 h-[calc(100%-30px)] w-px ${item.done ? "bg-teal-600" : "bg-border"}`}/>:null}<span className={`relative z-10 flex size-9 shrink-0 items-center justify-center rounded-full ${item.done ? "bg-teal-100 text-teal-800" : "bg-sand-100 text-inkSubtle"}`}><Icon size={17}/></span><div><p className={`text-sm font-bold ${item.done ? "text-ink" : "text-inkMuted"}`}>{item.title}</p><p className="mt-1 text-xs text-inkSubtle">{item.time}</p></div>{item.title==="Out for delivery"?<span className="ml-auto size-2 animate-pulse rounded-full bg-teal-600"/>:null}</div>})}</div></section><section className="rounded-2xl border border-border bg-surface p-5"><div className="flex items-center justify-between"><h2 className="font-display text-lg font-extrabold">Your order</h2><span className="text-xs font-bold text-brand">View receipt</span></div><div className="mt-4 space-y-3 text-sm text-inkMuted"><div className="flex justify-between"><span>1× Margherita D.O.P.</span><span>€14.50</span></div><div className="flex justify-between"><span>1× Roasted vegetables</span><span>€11.00</span></div><div className="flex justify-between"><span>1× Mediterranean bowl</span><span>€12.50</span></div></div><div className="mt-4 flex justify-between border-t border-border pt-4 font-extrabold"><span>Total paid</span><span>€32.90</span></div></section><div className="flex items-center gap-3 rounded-2xl border border-teal-200 bg-teal-50 p-4 text-teal-800"><Check size={18}/><p className="text-xs font-semibold leading-5">Contactless delivery selected. Alex will leave the order at your door.</p></div></aside></div>
  </>;
}

export function FoodieHubShowcase({ screen }: { screen: FoodieHubScreen }) {
  return <Shell screen={screen}>{screen === "discover" ? <Discover/> : screen === "checkout" ? <Checkout/> : <Tracking/>}</Shell>;
}
